// TEMPORARY DATA

export const studentsData = [
  {
    id: 1,
    studentId: "STU001",
    name: "Alice Johnson",
    photo: "https://images.pexels.com/photos/3771118/pexels-photo-3771118.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Com CS",
    semester: 1,
  },
  {
    id: 2,
    studentId: "STU002",
    name: "Bob Williams",
    photo: "https://images.pexels.com/photos/3762804/pexels-photo-3762804.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Com CS",
    semester: 1,
  },
  {
    id: 3,
    studentId: "STU003",
    name: "Charlie Brown",
    photo: "https://images.pexels.com/photos/3771092/pexels-photo-3771092.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.A. History",
    semester: 3,
  },
  {
    id: 4,
    studentId: "STU004",
    name: "Diana Miller",
    photo: "https://images.pexels.com/photos/3771100/pexels-photo-3771100.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.A. History",
    semester: 3,
  },
  {
    id: 5,
    studentId: "STU005",
    name: "Eve Davis",
    photo: "https://images.pexels.com/photos/3771113/pexels-photo-3771113.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Sc. Physics",
    semester: 5,
  },
  {
    id: 6,
    studentId: "STU006",
    name: "Frank White",
    photo: "https://images.pexels.com/photos/3771107/pexels-photo-3771107.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Sc. Physics",
    semester: 5,
  },
  {
    id: 7,
    studentId: "STU007",
    name: "Grace Taylor",
    photo: "https://images.pexels.com/photos/3771089/pexels-photo-3771089.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Com",
    semester: 1,
  },
  {
    id: 8,
    studentId: "STU008",
    name: "Henry Clark",
    photo: "https://images.pexels.com/photos/3771110/pexels-photo-3771110.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Com",
    semester: 1,
  },
  {
    id: 9,
    studentId: "STU009",
    name: "Ivy Lewis",
    photo: "https://images.pexels.com/photos/3771095/pexels-photo-3771095.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.Com",
    semester: 7,
  },
  {
    id: 10,
    studentId: "STU010",
    name: "Jack Robinson",
    photo: "https://images.pexels.com/photos/3771119/pexels-photo-3771119.jpeg?auto=compress&cs=tinysrgb&w=1200",
    program: "B.A",
    semester: 7,
  },
];

export const lecturersData = [
  {
    id: 1,
    lecturerId: "LEC001",
    name: "Mr. Smith",
    photo: "https://images.pexels.com/photos/3762810/pexels-photo-3762810.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Calculus I", "Classical Mechanics"],
  },
  {
    id: 2,
    lecturerId: "LEC002",
    name: "Ms. Jones",
    photo: "https://images.pexels.com/photos/3762800/pexels-photo-3762800.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Communicative English", "Modern History"],
  },
  {
    id: 3,
    lecturerId: "LEC003",
    name: "Dr. Lee",
    photo: "https://images.pexels.com/photos/3771120/pexels-photo-3771120.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Organic Chemistry", "Cell Biology"],
  },
  {
    id: 4,
    lecturerId: "LEC004",
    name: "Mrs. Kim",
    photo: "https://images.pexels.com/photos/3762812/pexels-photo-3762812.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["Data Structures", "Algorithms"],
  },
  {
    id: 5,
    lecturerId: "LEC005",
    name: "Mr. Brown",
    photo: "https://images.pexels.com/photos/3771115/pexels-photo-3771115.jpeg?auto=compress&cs=tinysrgb&w=1200",
    courses: ["History of Art", "Music Theory"],
  },
];